import { appNamespace } from '@/_constants/i18next/app-namespace';
import { pageSubNamespace } from '../../../_constants/page-sub-namespace';
import { TranslatedRegistrationFormTextType } from './_types';

export const FORM_TRANSLATED_TEXT: TranslatedRegistrationFormTextType = {
  allowFormatsPlaceholder: `${appNamespace}:${pageSubNamespace}.allowFormatsPlaceholder`,
  title: `${appNamespace}:${pageSubNamespace}.title`,
  buttonSubmit: `${appNamespace}:${pageSubNamespace}.buttonSubmit`,
  buttonCancel: `${appNamespace}:${pageSubNamespace}.buttonCancel`,
  legalFormID: `${appNamespace}:${pageSubNamespace}.legalForm`,
  legalFormPlaceholder: `${appNamespace}:${pageSubNamespace}.legalFormPlaceholder`,
  inn: `${appNamespace}:${pageSubNamespace}.inn`,
  innPlaceholder: `${appNamespace}:${pageSubNamespace}.innPlaceholder`,
  kpp: `${appNamespace}:${pageSubNamespace}.kpp`,
  kppPlaceholder: `${appNamespace}:${pageSubNamespace}.kppPlaceholder`,
  bin: `${appNamespace}:${pageSubNamespace}.bin`,
  binPlaceholder: `${appNamespace}:${pageSubNamespace}.binPlaceholder`,
  unp: `${appNamespace}:${pageSubNamespace}.unp`,
  unpPlaceholder: `${appNamespace}:${pageSubNamespace}.unpPlaceholder`,
  ogrn: `${appNamespace}:${pageSubNamespace}.ogrn`,
  ogrnPlaceholder: `${appNamespace}:${pageSubNamespace}.ogrnPlaceholder`,
  ogrnip: `${appNamespace}:${pageSubNamespace}.ogrnip`,
  ogrnipPlaceholder: `${appNamespace}:${pageSubNamespace}.ogrnipPlaceholder`,
  okpo: `${appNamespace}:${pageSubNamespace}.okpo`,
  okpoPlaceholder: `${appNamespace}:${pageSubNamespace}.okpoPlaceholder`,
  okopf: `${appNamespace}:${pageSubNamespace}.okopf`,
  okopfPlaceholder: `${appNamespace}:${pageSubNamespace}.okopfPlaceholder`,
  contactFullName: `${appNamespace}:${pageSubNamespace}.contactFullName`,
  contactFullNamePlaceholder: `${appNamespace}:${pageSubNamespace}.contactFullNamePlaceholder`,
  passportDoc: `${appNamespace}:${pageSubNamespace}.passportDoc`,
  passportDocPlaceholder: `${appNamespace}:${pageSubNamespace}.passportDocPlaceholder`,
  juridicalAddress: `${appNamespace}:${pageSubNamespace}.juridicalAddress`,
  juridicalAddressPlaceholder: `${appNamespace}:${pageSubNamespace}.juridicalAddressPlaceholder`,
  fullName: `${appNamespace}:${pageSubNamespace}.fullName`,
  fullNamePlaceholder: `${appNamespace}:${pageSubNamespace}.fullNamePlaceholder`,
  country: `${appNamespace}:${pageSubNamespace}.countryLabel`,
  countryID: `${appNamespace}:${pageSubNamespace}.countryID`,
  countryPlaceholder: `${appNamespace}:${pageSubNamespace}.countryPlaceholder`,
  mainInfo: `${appNamespace}:${pageSubNamespace}.mainInfo`,
  innInfo: `${appNamespace}:${pageSubNamespace}.innInfo`,
  photoContentTitle: `${appNamespace}:${pageSubNamespace}.photoContentTitle`,
  photoContentText: `${appNamespace}:${pageSubNamespace}.photoContentText`,
  name: `${appNamespace}:${pageSubNamespace}.name`,
  nameOrganizationPlaceholder: `${appNamespace}:${pageSubNamespace}.nameOrganizationPlaceholder`,
  nameIpPlaceholder: `${appNamespace}:${pageSubNamespace}.nameIpPlaceholder`,
  nameOrganizationTooltipText: `${appNamespace}:${pageSubNamespace}.nameOrganizationTooltipText`,
  nameIpTooltipText: `${appNamespace}:${pageSubNamespace}.nameIpTooltipText`,
  generalBusiness: `${appNamespace}:${pageSubNamespace}.generalBusiness`,
  generalOwn: `${appNamespace}:${pageSubNamespace}.generalOwn`,
  generalBusinessPlaceholder: `${appNamespace}:${pageSubNamespace}.generalBusinessPlaceholder`,
  generalOwnPlaceholder: `${appNamespace}:${pageSubNamespace}.generalOwnPlaceholder`,
};

export const FORM_FIELD_NAMES = {
  legalFormID: 'legalFormID',
  inn: 'inn',
  kpp: 'kpp',
  ogrn: 'ogrn',
  ogrnip: 'ogrnip',
  okpo: 'okpo',
  okopf: 'okopf',
  contactFullName: 'contactFullName',
  passportDoc: 'passportDoc',
  juridicalAddress: 'juridicalAddress',
  countryID: 'countryID',
  fullName: 'fullName',
  name: 'name',
  general: 'general',
  unp: 'unp',
  bin: 'bin',
};

export const FORM_FIELDS_WITH_ERRORS = {
  [FORM_FIELD_NAMES.legalFormID]: true,
  [FORM_FIELD_NAMES.inn]: true,
  [FORM_FIELD_NAMES.kpp]: true,
  [FORM_FIELD_NAMES.countryID]: true,
};

export const TIMEOUT_OPEN_FORM = 300;
